SanJose/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include
from django.contrib.auth import views
from django.views.generic import TemplateView
from django.contrib.auth.views import logout

from .views import error, crearingreso, crearradiologia, crearuci, crearneurologia, crearbold, crearinformante, \
    crearseguimiento, crearradiologiaf, crearmoca, crearnps, crearneuropsi, visionimagen, validarmovimiento, alinear, crearlectura

from .views import reportes, run_pipeline

urlpatterns = [
    path('', lambda x: HttpResponseRedirect('/login')),
    path('admin/', admin.site.urls),
    path('carga/', include('apps.fileupload.urls')),
    path('paciente/', include('apps.paciente.urls')),
    path('validacion/', include('apps.validacion.urls')),
    path('graficas/',include('apps.graphs.urls')),

    url(r'^login/$', views.login, name='login'),
    url(r'^accounts/logout/$', logout, {'template_name': 'registration/logout.html'},name='logout'),
    url(r'^login-error$', error, name='login-error'),
    path('report_builder/', include('report_builder.urls')),
    path('script/creari/<int:pk>/', crearingreso, name='crear_ingreso'),
    path('script/crearr/<int:pk>/', crearradiologia, name='crear_radiologia'),
    path('script/crearu/<int:pk>/', crearuci, name='crear_uci'),
    path('script/crearn/<int:pk>/', crearneurologia, name='crear_neurologia'),
    path('script/crearb/<int:pk>/', crearbold, name='crear_bold'),
    path('script/crearinf/<int:pk>/', crearinformante, name='crear_informante'),
    path('script/crears/<int:pk>/', crearseguimiento, name='crear_seguimiento'),
    path('script/crearrf/<int:pk>/<slug:razon>/', crearradiologiaf, name='crear_rf'),
    path('script/crearnps/<int:pk>/<slug:razon>/<slug:fecha>/', crearnps, name='crear_nps'),
    path('script/crearm/<int:pk>/', crearmoca, name='crear_moca'),
    path('script/crearnpsi/<int:pk>/', crearneuropsi, name='crear_neuropsi'),
    path('script/crearl/<int:pk>/<slug:tipo>/', crearlectura, name='crear_lectura'),
    path('script/filtros_img/<slug:pk>/', visionimagen, name='vision_img'),
    path('script/vmovimiento/<slug:tipo>/<int:pk>/<slug:v1>/<slug:v2>/', validarmovimiento, name='v_movimiento'),
    path('script/alinear/<slug:tipo>/<int:pk>/<slug:img>/<slug:der>/<slug:frente>/<slug:arriba>/<slug:x>/<slug:y>/<slug:z>/<slug:tx>/<slug:ty>/<slug:tz>/<slug:save>/', alinear, name='alinear'),

  
    url(r'^reportes$',reportes,name="reportes"),

    url(r'^visualizador', TemplateView.as_view(template_name='slicedrop/index.html'), name="visor"),

    url(r'^accounts/', include('allauth.urls')),
    
    path('procesamiento/', include('apps.procesamiento.urls')),
    
    path('script/run_pipeline/<int:user_pk>/<int:img_pk>/<int:pipeline_pk>/', run_pipeline, name='run_pipeline'),




]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/fileupload/urls.py
# encoding: utf-8
from django.urls import path
from apps.fileupload.views import PictureCreateView, PictureDeleteView, PictureListView

urlpatterns = [
    path('new/', PictureCreateView.as_view(), name='upload-new'),
    path('delete/<int:pk>', PictureDeleteView.as_view(), name='upload-delete'),
    #path('view/', PictureListView.as_view(), name='upload-view'),
]

apps/fileupload/models.py
# encoding: utf-8
import os
import shutil

from django.db import models
from django.contrib.auth.decorators import permission_required



class Picture(models.Model):
    """This is a small demo using just two fields. The slug field is really not
    necessary, but makes the code simpler. ImageField depends on PIL or
    pillow (where Pillow is easily installable in a virtualenv. If you have
    problems installing pillow, use a more generic FileField instead.

    """
    file = models.FileField(upload_to="Archivos")
    slug = models.SlugField(max_length=100, blank=True)
    anonimo = models.IntegerField(default=0,blank=True,null=True)
    def __str__(self):
        #return self.file.name
        return '{}'.format(self.slug)



    @models.permalink
    def get_absolute_url(self):
        return ('upload-new', )

    def save(self, *args, **kwargs):
        super(Picture, self).save(*args, **kwargs)

apps/fileupload/views.py
# encoding: utf-8
import json
import os
from fileinput import filename

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponse
from django.shortcuts import  redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView

from apps.paciente.models import Candidato, Control
from .models import Picture
from .response import JSONResponse, response_mimetype
from .serialize import serialize
from apps.paciente.templatetags.scripts import anonimizar

import logging

log=logging.getLogger('django')


class PictureCreateView(CreateView):
    model = Picture
    fields = "__all__"

    def form_valid(self, form):
        self.object = form.save()
        files = [serialize(self.object)]
        data = {'files': files}
        response = JSONResponse(data, mimetype=response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        sn=str(self.object.slug)
        if sn[0]=='c':
            c=Control.objects.get(numero=int(sn[1:]))
            os.mkdir(settings.MEDIA_ROOT+'/controles/control' + sn[1:] + "/imagenes")
            file = open(settings.MEDIA_ROOT+"/controles/control" + sn[1:] + "/" + sn[1:] + ".txt", "w")
            file.write("" + sn[1:]+"\n")
            file.close()
            c.imagen = "/controles/control" + sn[1:] + "/" + sn[1:] + ".txt"
            c.save()
            log.info("--------------------- Creacion Picture Control" + str(c.numero) + "---------------------")
            anonimizar.delay(sn)

        else:
            p=Candidato.objects.get(sujeto_numero=int(sn))
            if p.estado==1:
                os.mkdir(settings.MEDIA_ROOT+'/img/sujeto' + str(sn) + "/imagenes")
                p.estado=2
                file = open(settings.MEDIA_ROOT+"/img/sujeto" + str(sn) + "/" + str(sn) + ".txt", "w")
                file.write("" + str(sn)+"\n")
                file.close()
                p.imagen = "/img/sujeto" + str(sn) + "/" + str(sn) + ".txt"
                p.save()
                anonimizar.delay(sn)
            log.info("--------------------- Creacion Picture Sujeto" + str(p.sujeto_numero) + "---------------------")
        return response

    def form_invalid(self, form):
        data = json.dumps(form.errors)
        return HttpResponse(content=data, status=400, content_type='application/json')


class PictureDeleteView(PermissionRequiredMixin, DeleteView):
    permission_required = 'fileupload.delete_picture'
    model = Picture
    template_name = 'fileupload/eliminar.html'
    # a donde va dirigido
    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        response = JSONResponse(True, mimetype=response_mimetype(request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return redirect('upload-new')


class PictureListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    permission_required = 'fileupload.add_picture'
    model = Picture

    def render_to_response(self, context, **response_kwargs):
        files = [ serialize(p) for p in self.get_queryset() ]
        data = {'files': files}
        response = JSONResponse(data, mimetype=response_mimetype(self.request))
        response['Content-Disposition'] = 'inline; filename=files.json'
        return response

apps/fileupload/templates/fileupload/eliminar.html
{% extends 'upload_base.html' %}

{% block content %}
{% if user.groups.all.0.name != 'Coordinador' %}
<script type="text/javascript">
        window.location="{% url 'paciente_listar' %}";
</script>
{% endif %}
<center>
<div class="container">
    <form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el archivo del sujeto {{ object.slug}}?</h3>


    <button class="btn btn-danger" type="submit">Sí, eliminar</button>
    <a class="btn btn-success" href="{% url 'paciente_listar' %}">Cancelar</a>
</form>
</div>
</center>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/static/js/tmpl.min.js"></script>
<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
<script src="/static/js/bootstrap.min.js"></script>

<!-- The XDomainRequest Transport is included for cross-domain file deletion for IE8+ -->
<!--[if gte IE 8]>
<script src="/static/js/cors/jquery.xdr-transport.js"></script>
<![endif]-->

{% endblock %}

apps/fileupload/templates/fileupload/picture_form.html
{% extends "upload_base.html" %}
{% load upload_tags %}


{% block content %}
<div class="container">
    {% if user.groups.all.0.name != 'Consultor' %}
    <h1>Carga de archivos</h1>
    {% else %}
    <h1>Lista sujetos en el estudio</h1>
    {% endif %}
    <br>
    <!-- The file upload form used as target for the file upload widget -->
    <form id="fileupload" method="post" action="." enctype="multipart/form-data">{% csrf_token %}
        <!-- Redirect browsers with JavaScript disabled to the origin page -->
        <!--<noscript><input type="hidden" name="redirect" value="http://blueimp.github.io/jQuery-File-Upload/"></noscript>-->
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->

        {% if user.groups.all.0.name != 'Consultor' %}

        <div class="row fileupload-buttonbar" id="carga">
            <div class="col-lg-7" >
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button" id="add">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span >Añadir Archivos...</span>
                    <input type="file" name="file" >
                </span>
                <button type="submit" class="btn btn-primary start" id="go" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Cargar</span>
                </button>




                <!-- The loading indicator is shown during file processing -->
                <span class="fileupload-loading"></span>
            </div>
            <!-- The global progress information -->
            <div class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->

                <!-- The extended global progress information -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        {% endif %}
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped" id="table"><tbody class="files"></tbody></table>
        <p id="resultado" style="display:none"></p>
        <input type="text" name="slug" maxlength="100" id="id_slug" hidden/>
        {% img as my_array %}

{% for item in my_array %}

        <script type="text/javascript">
            var a="{{ forloop.counter }}";
            var x="{{item}}";
            var y=window.parent.document.getElementById("sn").value;
            if (a == y && x == 1){
            document.getElementById("carga").style="display:none";
            document.getElementById("resultado").style="display:inline";
            document.getElementById("resultado").innerHTML="Archivo Cargado Satisfactoriamente "+String(y);
            }
        </script>

{% endfor %}

        {% imgc as myarray %}

{% for item in myarray %}

        <script type="text/javascript">
            var y=window.parent.document.getElementById("sn").value;
            if ( y.substring(0,1) == 'c' ){
                var a="{{ forloop.counter }}";
                var x="{{item}}";
                y=y.substring(1, );
                if (a == y && x == 1){
                document.getElementById("carga").style="display:none";
                document.getElementById("resultado").style="display:inline";
                document.getElementById("resultado").innerHTML="Archivo Cargado Satisfactoriamente "+String(y);
            }

            }
        </script>

{% endfor %}

    </form>
    <br>

<script type="text/javascript">

      var x=window.parent.document.getElementById("sn").value;
      document.getElementById("id_slug").value=x;

      document.getElementById("go").addEventListener('click', ocultar);
      document.getElementById("add").addEventListener('click', habilitar);

    /* function */
    function ocultar(){
    document.getElementById("add").style="display:none";
    document.getElementById("go").style="display:none";
    }
    function habilitar(){
    document.getElementById("add").style="display:none";
    document.getElementById("go").disabled=false;
    }
</script>
<script>
    if (document.getElementById("id_slug").value==""){
      window.location="{% url 'paciente_listar' %}";
      }
</script>
</div>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>

{% upload_js user.groups.all.0.name %}



<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/static/js/vendor/jquery.ui.widget.js"></script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="/static/js/tmpl.min.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="/static/js/load-image.min.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="/static/js/canvas-to-blob.min.js"></script>
<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
<script src="/static/js/bootstrap.min.js"></script>
<!-- blueimp Gallery script -->
<script src="/static/js/jquery.blueimp-gallery.min.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="/static/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script id="drag" src="/static/js/jquery.fileupload.js" var1="{{ user.groups.all.0  }}"></script>
<!-- The File Upload processing plugin -->
<script src="/static/js/jquery.fileupload-process.js"></script>
<!-- The File Upload image preview & resize plugin -->
<script src="/static/js/jquery.fileupload-image.js"></script>
<!-- The File Upload audio preview plugin -->
<script src="/static/js/jquery.fileupload-audio.js"></script>
<!-- The File Upload video preview plugin -->
<script src="/static/js/jquery.fileupload-video.js"></script>
<!-- The File Upload validation plugin -->
<script src="/static/js/jquery.fileupload-validate.js"></script>
<!-- The File Upload user interface plugin -->
<script src="/static/js/jquery.fileupload-ui.js"></script>
<!-- The main application script -->
<script src="/static/js/main.js"></script>
<script src="/static/js/locale.js"></script>
<script src="/static/js/csrf.js"></script>
<!-- The XDomainRequest Transport is included for cross-domain file deletion for IE8+ -->
<!--[if gte IE 8]>
<script src="/static/js/cors/jquery.xdr-transport.js"></script>
<![endif]-->
{% endblock %}