SanJose/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include
from django.contrib.auth import views
from django.views.generic import TemplateView
from django.contrib.auth.views import logout

from .views import error, crearingreso, crearradiologia, crearuci, crearneurologia, crearbold, crearinformante, \
    crearseguimiento, crearradiologiaf, crearmoca, crearnps, crearneuropsi, visionimagen, validarmovimiento, alinear, crearlectura

from .views import reportes, run_pipeline

urlpatterns = [
    path('', lambda x: HttpResponseRedirect('/login')),
    path('admin/', admin.site.urls),
    path('carga/', include('apps.fileupload.urls')),
    path('paciente/', include('apps.paciente.urls')),
    path('validacion/', include('apps.validacion.urls')),
    path('graficas/',include('apps.graphs.urls')),

    url(r'^login/$', views.login, name='login'),
    url(r'^accounts/logout/$', logout, {'template_name': 'registration/logout.html'},name='logout'),
    url(r'^login-error$', error, name='login-error'),
    path('report_builder/', include('report_builder.urls')),
    path('script/creari/<int:pk>/', crearingreso, name='crear_ingreso'),
    path('script/crearr/<int:pk>/', crearradiologia, name='crear_radiologia'),
    path('script/crearu/<int:pk>/', crearuci, name='crear_uci'),
    path('script/crearn/<int:pk>/', crearneurologia, name='crear_neurologia'),
    path('script/crearb/<int:pk>/', crearbold, name='crear_bold'),
    path('script/crearinf/<int:pk>/', crearinformante, name='crear_informante'),
    path('script/crears/<int:pk>/', crearseguimiento, name='crear_seguimiento'),
    path('script/crearrf/<int:pk>/<slug:razon>/', crearradiologiaf, name='crear_rf'),
    path('script/crearnps/<int:pk>/<slug:razon>/<slug:fecha>/', crearnps, name='crear_nps'),
    path('script/crearm/<int:pk>/', crearmoca, name='crear_moca'),
    path('script/crearnpsi/<int:pk>/', crearneuropsi, name='crear_neuropsi'),
    path('script/crearl/<int:pk>/<slug:tipo>/', crearlectura, name='crear_lectura'),
    path('script/filtros_img/<slug:pk>/', visionimagen, name='vision_img'),
    path('script/vmovimiento/<slug:tipo>/<int:pk>/<slug:v1>/<slug:v2>/', validarmovimiento, name='v_movimiento'),
    path('script/alinear/<slug:tipo>/<int:pk>/<slug:img>/<slug:der>/<slug:frente>/<slug:arriba>/<slug:x>/<slug:y>/<slug:z>/<slug:tx>/<slug:ty>/<slug:tz>/<slug:save>/', alinear, name='alinear'),

  
    url(r'^reportes$',reportes,name="reportes"),

    url(r'^visualizador', TemplateView.as_view(template_name='slicedrop/index.html'), name="visor"),

    url(r'^accounts/', include('allauth.urls')),
    
    path('procesamiento/', include('apps.procesamiento.urls')),
    
    path('script/run_pipeline/<int:user_pk>/<int:img_pk>/<int:pipeline_pk>/', run_pipeline, name='run_pipeline'),




]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/paciente/models.py
import datetime
import shutil

from django.conf import settings
from django.db import models

# Create your models here.
from django.utils import timezone

from apps.fileupload.models import Picture
from apps.validacion.models import Realineacion, Snr, img_to_show
from programas import definitions


class Dprevio(models.Model):
    Traumaticos = "Traumáticos"
    Degenerativos = "Degenerativos"
    Neoplasticos = "Neoplásticos"
    Vasculares = "Vasculares"
    Infecciosos = "Infecciosos"
    Metabolicos = "Metabólicos"
    Tx_Neurodesarrollo = "Tx Neurodesarrollo"
    Tx_Psicótico = "TX Psicótico"
    Tx_Afectivo = "Tx Afectivo"
    Deficit = "Deficit cognitivo"
    Abuso = "Abuso de sustancias"
    Otro = "Otro"
    D_neuro_logico_psiquiatrico_previo_choices = (
    (Traumaticos, u"Traumáticos"), (Degenerativos, u"Degenerativos"), (Neoplasticos, u"Neoplásticos"),
    (Vasculares, u"Vasculares"), (Infecciosos, u"Infecciosos"), (Metabolicos, u"Metabólicos"),
    (Tx_Neurodesarrollo, u"Tx Neurodesarrollo"), (Tx_Psicótico, u"TX Psicótico"),
    (Tx_Afectivo, u"Tx Afectivo"), (Deficit, u"Deficit cognitivo"), (Abuso, u"Abuso de sustancias"),
    (Otro, u"Otro"))
    nombre=models.CharField(max_length=50, choices=D_neuro_logico_psiquiatrico_previo_choices)

    def __str__(self):
        return '{}'.format(self.nombre)
    class ReportBuilder:
        exclude = ('id', )  # Lists or tuple of excluded fields


class Apatologicos(models.Model):
    hta='HTA'
    diabetes='Diabetes'
    iam='IAM'
    hipotiroidismo='Hipotiroidismo'
    dislipidemia= 'Dislipidemia'
    otro='Otro'

    Apatologicos_choices= ((hta,u"HTA"),(diabetes,u"Diabetes"),(iam,u"IAM"),(hipotiroidismo,u"Hipotiroidismo"),(dislipidemia,u"Dislipidemia"),(otro,u"Otro"))
    nombre=models.CharField(max_length=50, choices=Apatologicos_choices)

    def __str__(self):
        return '{}'.format(self.nombre)
    class ReportBuilder:
        exclude = ('id', )  # Lists or tuple of excluded fields

class Medico(models.Model):
    nombre = models.CharField(max_length=70)

    def get_pacientes(self):
        return self.candidato_set.all()
    def __str__(self):
        return '{}'.format(self.nombre)
    class ReportBuilder:
        exclude = ('id', )  # Lists or tuple of excluded fields
class Candidato(models.Model):
    sujeto_numero = models.PositiveIntegerField(null=True, unique=True)
    fecha_de_registro= models.DateField(null=True, default=timezone.now)
    cc = models.PositiveIntegerField(null=True, unique=True)
    nombres = models.CharField(null=True, max_length=50, default="")
    apellidos = models.CharField(null=True, max_length=50, default="")
    fecha_nacimiento = models.DateField(null=True)
    edad = models.PositiveIntegerField(null=True)
    #######sexo
    hombre = 'Hombre'
    mujer = 'Mujer'
    Sexo_choices = ((hombre, u'Hombre'), (mujer, u'Mujer'))
    sexo = models.CharField(max_length=9, choices=Sexo_choices, null=True)
    ######
    HC = models.PositiveIntegerField(null=True, unique=True)
    cama_numero =models.PositiveIntegerField(null=True)
    fecha_evento_principal = models.DateField(null=True)
    hora_evento_principal = models.TimeField(blank=True, null=True)
    fecha_hora_ingreso = models.DateTimeField(null=True)

    ######## Grupo diagnostico
    TCE='TCE'
    H_A='Hipoxia/Anoxia'
    ACV='ACV'
    G_diagnostico_choices=((TCE, u'TCE'),(H_A, u'Hipoxia/Anoxia'),(ACV, u'ACV'))
    G_diagnostico=models.CharField(max_length=20, choices=G_diagnostico_choices, null=True)
    ######## Diagnosticos neuro / psiquiatricos previos
    D_neuro_logico_psiquiatrico_previo=models.ManyToManyField(Dprevio, blank=True)
    ###### Especificacion diagnosticos
    D_especificos = models.TextField(blank=True, null=True)
    ######## criterios de inclusion
    criterios_CHOICES = (
        ('Paciente con episodio de parada cardíaca con reanimación exitosa', 'Paciente con episodio de parada cardíaca con reanimación exitosa'),
        ('Paciente con Dx de lesión cerebral aguda de origen traumático', 'Paciente con Dx de lesión cerebral aguda de origen traumático'),
        ('Paciente con Dx de lesión cerebral aguda por evento cerebrovascular', 'Paciente con Dx de lesión cerebral aguda por evento cerebrovascular'),

    )
    ci = models.CharField(choices=criterios_CHOICES, max_length=128, null=True, default='Paciente con episodio de parada cardíaca con reanimación exitosa',blank=True)
    ci3 = models.NullBooleanField('Puntaje en escala Glasgow igual o menor a 8 después del evento inicial')
    ci4=models.NullBooleanField("Paciente transportable a un resonador")

    ####### Criterios de exclusion
    ce1=models.NullBooleanField("Diagnóstico de muerte cerebral en las primeras 48 horas del ingreso a UCI")
    ce2=models.NullBooleanField("Destruccion masiva del parénquima cerebral no rescatable por neurocirugía")
    ce3=models.NullBooleanField("Disfunción neurológica y/o neuropsiquiátrica previa")
    ce4=models.NullBooleanField("Decisión de la familia de no participar en estudios de investigación")
    #######
    #######resultado


    medico_responsable=models.ForeignKey(Medico, on_delete=models.SET_NULL, null=True)
    imagen = models.FileField(null=True, upload_to="img",blank=True)
    estado = models.PositiveIntegerField(null=True, default=0)
    inscrito = models.NullBooleanField(default=False)
    archivo = models.FileField(null=True, upload_to="img", blank=True)

    def __str__(self):
        return '{}'.format(self.sujeto_numero)

    def get_seguimiento(self):
        return self.seguimiento_set.all().order_by('fechaseguimiento')
    def get_radio(self):
        return self.cambioradiologia_set.all()
    def get_neuro(self):
        return self.neurologia_set.all().order_by('fechaneuro')
    def get_img(self):
        i=Picture.objects.get(slug=self.sujeto_numero)
        return i
    def get_realineacion(self):
        realineacion=Realineacion.objects.get(sujeto=self.sujeto_numero)
        return realineacion
    def get_snr(self):
        snr=Snr.objects.get(sujeto=self.sujeto_numero)
        return snr
    
    def get_path_imgs(self):
        I=img_to_show.objects.filter(sujeto=self.sujeto_numero)
        return I
    
    

    def delete(self, *args, **kwargs):
        """delete -- Remove to leave file."""
        c = self
        n=c.sujeto_numero
        shutil.rmtree(settings.MEDIA_ROOT+"/img/sujeto"+str(n), ignore_errors=True)
        super(Candidato, self).delete(*args, **kwargs)
        try:
            i=Picture.objects.get(slug=str(n))
            i.delete()
        except:
            ""

    class Meta:
        permissions = (
            ("can_descargar_candidato", u"puede descargar candidato"),
        )

    class ReportBuilder:
        exclude = ('nombres','apellidos','cc','imagen','id', 'archivo', )  # Lists or tuple of excluded fields


class Ingreso(models.Model):
    candidato = models.OneToOneField(Candidato, on_delete=models.CASCADE, null=True)
    fecha_form = models.DateField(null=True)
    lugar_nacimiento = models.CharField(max_length=80, null=True, default="")
    lugar_residencia = models.CharField(max_length=80, null=True, default="")
    direccion = models.CharField(max_length=60, null=True, blank=True)
    nombre_acompanante = models.CharField(max_length=50,null=True, default="")
    tel1 = models.PositiveIntegerField(null=True)
    tel2 = models.PositiveIntegerField(null=True, blank=True)
    peso =models.PositiveIntegerField(null=True, blank=True)
    estatura = models.PositiveIntegerField(null=True, blank=True)
    ####### nivel educativo
    Analfabeta = 'Analfabeta'
    primaria = 'Primaria'
    bachillerato = 'Bachillerato'
    tecnico = 'Técnico'
    profesional = 'Profesional'
    educativo_choices = ((Analfabeta, u'Analfabeta'),(primaria, u'Primaria'), (bachillerato, u'Bachillerato'), (tecnico, u'Técnico'), (profesional, u'Profesional'))
    n_educativo = models.CharField(max_length=20, choices=educativo_choices, null=True)
    ######
    ####### lateralidad
    diestro = 'Diestro'
    zurdo = 'Zurdo'
    ambidiestro = 'Ambidiestro'
    lateralidad_choices = ((diestro, u'Diestro'), (zurdo, u'Zurdo'), (ambidiestro, u'Ambidiestro'))
    lateralidad = models.CharField(max_length=20, choices=lateralidad_choices, null=True)
    ######
    ####### conciencia
    coma = 'Coma'
    svsr = 'SVSR'
    emc = 'EMC'
    conciencia_choices = ((coma, u'Coma'), (svsr, u'SVSR'), (emc, u'EMC'))
    conciencia = models.CharField(max_length=20, choices=conciencia_choices, null=True)
    ######
    sedado=models.NullBooleanField("Sedado por neuroprotección")
    a_patologicos = models.ManyToManyField(Apatologicos, blank=True)
    a_patologicos_cual= models.CharField(max_length=50, null=True,blank=True)


    fecha_craneotomia=models.DateField(blank=True, null=True)
    causa_quirurgicos = models.CharField(max_length=100, null=True, blank=True)

    a_toxico_alergenicos= models.CharField(max_length=50, null=True, blank=True)
    a_farmaco1=models.CharField(max_length=50, null=True, blank=True)
    a_farmaco1_dosis=models.CharField(max_length=30, null=True, blank=True)
    a_farmaco2 = models.CharField(max_length=50, null=True, blank=True)
    a_farmaco2_dosis = models.CharField(max_length=30, null=True, blank=True)
    a_familiares=models.CharField(max_length=50, null=True, blank=True)
    firma_consentimiento=models.BooleanField(default=True)
    firma_causa=models.CharField(max_length=50, null=True,blank=True)
    fechafirma=models.DateField(null=True, blank=True)
    archivo = models.FileField(null=True, upload_to="img", blank=True)
    archivofirma = models.FileField(null=True, upload_to="img", blank=True)

    def __str__(self):
        return '{}'.format(self.candidato.sujeto_numero)

    def delete(self, *args, **kwargs):
        """delete -- Remove to leave file."""
        self.archivo.delete(False)
        super(Ingreso, self).delete(*args, **kwargs)
    class Meta:
        permissions = (

templates/base/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="es">

<head>
	<!-- Force latest IE rendering engine or ChromeFrame if installed -->
    <!--[if IE]>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <![endif]-->
	<meta charset="UTF-8">


	{% block extrastatic %}
	{% endblock %}
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
	<link rel="stylesheet" href="/static/css/blueimp-gallery.min.css">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">







	<title>{% block title %}Document {% endblock %}</title>
</head>


{% if user.is_authenticated %}

		 <body oncopy="return false" onpaste="return false">

		 <div class="container" style="text-align:left;">
		 <p class="display-4">Usuario, {{ user.first_name }} {{ user.last_name }}</p>
		 {{ user.groups.all.0  }}
	     {% load scripts %}
         {% load scripts_procesamiento %}
		 {% crearDprevios %}
		 {% creargrupos %}
		 {% crearmedia %}
         {% tareas_defecto %}
             
		 {% edad %}


		 </div>
		 <br>

		 {% if user.groups.all.0.name != 'Invitado' %}
			<div class="container">

				{% block navbar %}

					<div class="bs-docs-section clearfix">
						<div class="row">
							<div class="col-lg-12">
								<div class="bs-component">
									<nav class="navbar navbar-default">
										<div class="container-fluid">
											<div class="navbar-header">
												<a class="navbar-brand" href="{% url 'paciente_listar' %}">Inicio</a>
											</div>

										<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
											<ul class="nav navbar-nav">
												<!--<li class="dropdown">
                                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sujetos <span class="caret"></span></a>
                                                    <ul class="dropdown-menu" role="menu">
														{% if user.groups.all.0.name != 'Consultor' %}
															<li><a href={% url "paciente_crear" %}>Añadir</a></li>
														{% endif %}
                                                        <li><a href={% url "paciente_listar" %}>Listar</a></li>
                                                    </ul>
                                                </li>-->
												<li class="dropdown">
                                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Controles <span class="caret"></span></a>
                                                    <ul class="dropdown-menu" role="menu">
														{% if perms.paciente.add_control %}
                                                        <li><a href="{% url 'control_crear' %}">Añadir</a></li>
														{% endif %}
														<li><a href="{% url 'controles_listar' %}">Lista</a></li>
                                                    </ul>
                                                </li>
												<li class="dropdown">
                                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Profesionales <span class="caret"></span></a>
                                                    <ul class="dropdown-menu" role="menu">
														{% if perms.paciente.add_medico %}
                                                        <li><a href="{% url 'medico_crear' %}">Añadir</a></li>
														{% endif %}
														<li><a href="{% url 'medico_listar' %}">Lista</a></li>
                                                    </ul>
                                                </li>
                                                {% if user.is_superuser %}
                                                <li class="dropdown">
                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Pipelines <span class="caret"></span></a>
                                                <ul class="dropdown-menu" role="menu">
													
                                                    <li><a href="{% url 'multi_run' %}">Ejecutar</a></li>
                                                    <li><a href="{% url 'grupo_listar' %}">Lista Pipelines</a></li>
													
													
                                                </ul>
                                            </li>
                                                {% endif%}

                                                <li class="dropdown">
	                                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Gráficas <span class="caret"></span></a>
	                                                <ul class="dropdown-menu" role="menu">
														
	                                                    <li><a href="{% url 'graph_dash' %}">Reclutamiento</a></li>
	                                                    <li><a href="{% url 'graph_demografico' %}">Información Demográfica</a></li>
	                                                    <li><a href="{% url 'graph_clinica' %}">Información Clínica</a></li>
                                                        <ul>
                                                            <li><a href="{% url 'graph_neurologia' %}">Neurología</a></li>
                                                            <li><a href="{% url 'graph_neuropsicologia' %}">Neuropsicología</a></li>
                                                            
                                                        </ul>

	                                                    
														
														
	                                                </ul>
	                                            </li>


                                                


												
												{% if user.is_staff %}
												<li><a href="{% url 'reportes' %}">Reportes</a></li>
												{%endif%}

											</ul>
											<ul class="nav navbar-nav navbar-right">
												<li><a href="{% url 'logout' %}">Salir</a></li>

											</ul>
										</div>
									</div>
								</nav>
							</div>
						</div>
					</div>
				</div>




				{% endblock %}


				{% block content %}
				<h4>	Bloque de contenido		</h4>
				{% endblock %}


				{% block footer %}
				{% endblock%}
			</div>



				{% block extrajs %}
				{% endblock %}
		 {% else %}
		 <div class="container">
			 <h1>Bienvenido</h1>
			 <p>Su cuenta a sido creada satisfactoriamente comuniquese con el Coordinador al correo <a href="#">cpulido@unal.edu.co</a> identificandose para
			 otorgarle los correspondientes permisos para el uso de la plataforma.</p>
			<a href="{% url 'logout'%}">Salir</a>
		 </div>

        {% endif %}



		<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>


		</body>
{% else %}
		 <script type="text/javascript">
        window.location="{% url 'login' %}";
        </script>
{% endif %}

</html>

templates/base/reportes.html
{% extends 'base/base.html' %}



{% block title %} Reportes {% endblock %}
{% block content %}

{% if user.is_staff == False %}
<script type="text/javascript">
        window.location="{% url 'paciente_listar' %}";
</script>
{% endif %}



<iframe src="{% url 'report_builder' %}" width="100%" height="800"  name="reportes" frameborder="0" >

{% endblock %}

templates/base/slice.html
{% extends 'base/base.html' %}



{% block title %} Visualización {% endblock %}
{% block content %}

{% if not perms.validacion.can_ver_slice %}
<script type="text/javascript">
        window.location="{% url 'paciente_listar' %}";
</script>
{% endif %}



<h3> Visualizador de imágenes {% if object.sujeto_numero %} Sujeto {{object.sujeto_numero}} {% elif object.numero %} Control {{object.numero }} {% endif %}</h3>


{% load scripts %}
{% load scripts_procesamiento %}


<h4>Seleccione Imagen a Mostrar</h4>

<select name="imagen" onchange="cargar()" id="selector"> 
  
  <option value="" selected >-----------</option>
      {% for s in object.get_path_imgs %}
        <option value="{{s.path}}">{{s.imagen}}</option>
    {% endfor%}
</select>

<br>
<br>

<button onclick="reload()">Reiniciar</button>
<br>

{% if perms.validacion.can_ver_parametrosimg  and object.parametrosmotioncorrect %}
    <div >
           
        {% get_pipelines as pipe %}
      
            {% for p in pipe %}
            {% get_estado_pipeline p object.get_img as task_c%}
                            
        {% if task_c %}         
                                      
                   {% if  perms.procesamiento.can_ver_resultados %}
                                     
                   
                   {% if task_c.0.estado == 'Finalizado'%}
                <form>
                  <button class="btn btn-primary" formaction="{% url 'resultados' task_c.0.pk %}" title="Ver Resultados">Ver Resultados {{p.nombre}}</button>
                  
                   </form>
                       {% endif%}

                    {% endif %}
     
                   
                   {% endif %}
        <br>
               
            {% endfor %}  
         

    </div>
      {% endif%}




<script>
	function cargar(){
	 	 a=document.getElementById('visor');
         b=document.getElementById('selector');
        
	 	 a.contentDocument.getElementById("archivo").value=b.value;
        
         a.contentWindow.carga();
         

	}
    
    function reload(){
	 	 a=document.getElementById('visor');
         a.contentWindow.location.reload(true);
         b=document.getElementById('selector').value="";
                  

	}

</script>


<br>

<br>



<iframe src="{% url 'visor' %}" width="100%" height="1000"  id="visor" frameborder="0" >





{% endblock %}