SanJose/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include
from django.contrib.auth import views
from django.views.generic import TemplateView
from django.contrib.auth.views import logout

from .views import error, crearingreso, crearradiologia, crearuci, crearneurologia, crearbold, crearinformante, \
    crearseguimiento, crearradiologiaf, crearmoca, crearnps, crearneuropsi, visionimagen, validarmovimiento, alinear, crearlectura

from .views import reportes, run_pipeline

urlpatterns = [
    path('', lambda x: HttpResponseRedirect('/login')),
    path('admin/', admin.site.urls),
    path('carga/', include('apps.fileupload.urls')),
    path('paciente/', include('apps.paciente.urls')),
    path('validacion/', include('apps.validacion.urls')),
    path('graficas/',include('apps.graphs.urls')),

    url(r'^login/$', views.login, name='login'),
    url(r'^accounts/logout/$', logout, {'template_name': 'registration/logout.html'},name='logout'),
    url(r'^login-error$', error, name='login-error'),
    path('report_builder/', include('report_builder.urls')),
    path('script/creari/<int:pk>/', crearingreso, name='crear_ingreso'),
    path('script/crearr/<int:pk>/', crearradiologia, name='crear_radiologia'),
    path('script/crearu/<int:pk>/', crearuci, name='crear_uci'),
    path('script/crearn/<int:pk>/', crearneurologia, name='crear_neurologia'),
    path('script/crearb/<int:pk>/', crearbold, name='crear_bold'),
    path('script/crearinf/<int:pk>/', crearinformante, name='crear_informante'),
    path('script/crears/<int:pk>/', crearseguimiento, name='crear_seguimiento'),
    path('script/crearrf/<int:pk>/<slug:razon>/', crearradiologiaf, name='crear_rf'),
    path('script/crearnps/<int:pk>/<slug:razon>/<slug:fecha>/', crearnps, name='crear_nps'),
    path('script/crearm/<int:pk>/', crearmoca, name='crear_moca'),
    path('script/crearnpsi/<int:pk>/', crearneuropsi, name='crear_neuropsi'),
    path('script/crearl/<int:pk>/<slug:tipo>/', crearlectura, name='crear_lectura'),
    path('script/filtros_img/<slug:pk>/', visionimagen, name='vision_img'),
    path('script/vmovimiento/<slug:tipo>/<int:pk>/<slug:v1>/<slug:v2>/', validarmovimiento, name='v_movimiento'),
    path('script/alinear/<slug:tipo>/<int:pk>/<slug:img>/<slug:der>/<slug:frente>/<slug:arriba>/<slug:x>/<slug:y>/<slug:z>/<slug:tx>/<slug:ty>/<slug:tz>/<slug:save>/', alinear, name='alinear'),

  
    url(r'^reportes$',reportes,name="reportes"),

    url(r'^visualizador', TemplateView.as_view(template_name='slicedrop/index.html'), name="visor"),

    url(r'^accounts/', include('allauth.urls')),
    
    path('procesamiento/', include('apps.procesamiento.urls')),
    
    path('script/run_pipeline/<int:user_pk>/<int:img_pk>/<int:pipeline_pk>/', run_pipeline, name='run_pipeline'),




]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/paciente/urls.py
from django.urls import path

from apps.paciente.views import PacienteCreate, PacienteUpdate, MedicoCreate, MedicoList, MedicoUpdate, MedicoDelete, \
    PacienteList, PacienteView, PacienteDelete, IngresoUpdate, RadiologiaUpdate, UciUpdate, NeurologiaUpdate, \
    BoldUpdate, MayorUpdate, InformanteUpdate, SeguimientoUpdate, ControlView, ControlList, ControlDelete, \
    ControlCreate, ControlUpdate, MocaUpdate, NeuropsiUpdate, LecturaUpdate, PacienteViewImg, ControlViewImg

urlpatterns = [

    path('nuevo', PacienteCreate.as_view(), name='paciente_crear'),
    path('control', ControlCreate.as_view(), name='control_crear'),
    path('editar/<int:pk>/', PacienteUpdate.as_view(), name='paciente_editar'),
    path('control/editar/<int:pk>/', ControlUpdate.as_view(), name='control_editar'),
    path('formularios/<slug:pk>', PacienteView.as_view(), name='paciente'),
    path('controles/<slug:pk>', ControlView.as_view(), name='control'),
    path('listar/', PacienteList.as_view(), name='paciente_listar'),
    path('controles/', ControlList.as_view(), name='controles_listar'),
    path('eliminar/<int:pk>/', PacienteDelete.as_view(), name='paciente_eliminar'),
    path('controles/eliminar/<int:pk>/', ControlDelete.as_view(), name='control_eliminar'),
    path('medico/nuevo', MedicoCreate.as_view(), name='medico_crear'),
    path('medico/listar', MedicoList.as_view(), name='medico_listar'),
    path('medico/editar/<int:pk>/', MedicoUpdate.as_view(), name='medico_editar'),
    path('medico/eliminar/<int:pk>/', MedicoDelete.as_view(), name='medico_eliminar'),
    path('ingreso/editar/<int:pk>/', IngresoUpdate.as_view(), name='ingreso_editar'),
    path('radiologia/editar/<int:pk>/', RadiologiaUpdate.as_view(), name='radiologia_editar'),
    path('uci/editar/<int:pk>/', UciUpdate.as_view(), name='uci_editar'),
    path('neurologia/editar/<int:pk>/', NeurologiaUpdate.as_view(), name='neurologia_editar'),
    path('bold/editar/<int:pk>/', BoldUpdate.as_view(), name='bold_editar'),
    path('mayor/editar/<int:pk>/', MayorUpdate.as_view(), name='mayor_editar'),
    path('informante/editar/<int:pk>/', InformanteUpdate.as_view(), name='informante_editar'),
    path('seguimiento/editar/<int:pk>/', SeguimientoUpdate.as_view(), name='seguimiento_editar'),
    path('moca/editar/<int:pk>/', MocaUpdate.as_view(), name='moca_editar'),
    path('neuropsi/editar/<int:pk>/', NeuropsiUpdate.as_view(), name='neuropsi_editar'),
    path('lectura/editar/<int:pk>/', LecturaUpdate.as_view(), name='lectura_editar'),
    path('visor_s/<slug:pk>', PacienteViewImg.as_view(), name='pacienteviewimg'),
    path('visor_c/<slug:pk>', ControlViewImg.as_view(), name='controlviewctl'),


]

apps/paciente/models.py
import datetime
import shutil

from django.conf import settings
from django.db import models

# Create your models here.
from django.utils import timezone

from apps.fileupload.models import Picture
from apps.validacion.models import Realineacion, Snr, img_to_show
from programas import definitions


class Dprevio(models.Model):
    Traumaticos = "Traumáticos"
    Degenerativos = "Degenerativos"
    Neoplasticos = "Neoplásticos"
    Vasculares = "Vasculares"
    Infecciosos = "Infecciosos"
    Metabolicos = "Metabólicos"
    Tx_Neurodesarrollo = "Tx Neurodesarrollo"
    Tx_Psicótico = "TX Psicótico"
    Tx_Afectivo = "Tx Afectivo"
    Deficit = "Deficit cognitivo"
    Abuso = "Abuso de sustancias"
    Otro = "Otro"
    D_neuro_logico_psiquiatrico_previo_choices = (
    (Traumaticos, u"Traumáticos"), (Degenerativos, u"Degenerativos"), (Neoplasticos, u"Neoplásticos"),
    (Vasculares, u"Vasculares"), (Infecciosos, u"Infecciosos"), (Metabolicos, u"Metabólicos"),
    (Tx_Neurodesarrollo, u"Tx Neurodesarrollo"), (Tx_Psicótico, u"TX Psicótico"),
    (Tx_Afectivo, u"Tx Afectivo"), (Deficit, u"Deficit cognitivo"), (Abuso, u"Abuso de sustancias"),
    (Otro, u"Otro"))
    nombre=models.CharField(max_length=50, choices=D_neuro_logico_psiquiatrico_previo_choices)

    def __str__(self):
        return '{}'.format(self.nombre)
    class ReportBuilder:
        exclude = ('id', )  # Lists or tuple of excluded fields


class Apatologicos(models.Model):
    hta='HTA'
    diabetes='Diabetes'
    iam='IAM'
    hipotiroidismo='Hipotiroidismo'
    dislipidemia= 'Dislipidemia'
    otro='Otro'

    Apatologicos_choices= ((hta,u"HTA"),(diabetes,u"Diabetes"),(iam,u"IAM"),(hipotiroidismo,u"Hipotiroidismo"),(dislipidemia,u"Dislipidemia"),(otro,u"Otro"))
    nombre=models.CharField(max_length=50, choices=Apatologicos_choices)

    def __str__(self):
        return '{}'.format(self.nombre)
    class ReportBuilder:
        exclude = ('id', )  # Lists or tuple of excluded fields

class Medico(models.Model):
    nombre = models.CharField(max_length=70)

    def get_pacientes(self):
        return self.candidato_set.all()
    def __str__(self):
        return '{}'.format(self.nombre)
    class ReportBuilder:
        exclude = ('id', )  # Lists or tuple of excluded fields
class Candidato(models.Model):
    sujeto_numero = models.PositiveIntegerField(null=True, unique=True)
    fecha_de_registro= models.DateField(null=True, default=timezone.now)
    cc = models.PositiveIntegerField(null=True, unique=True)
    nombres = models.CharField(null=True, max_length=50, default="")
    apellidos = models.CharField(null=True, max_length=50, default="")
    fecha_nacimiento = models.DateField(null=True)
    edad = models.PositiveIntegerField(null=True)
    #######sexo
    hombre = 'Hombre'
    mujer = 'Mujer'
    Sexo_choices = ((hombre, u'Hombre'), (mujer, u'Mujer'))
    sexo = models.CharField(max_length=9, choices=Sexo_choices, null=True)
    ######
    HC = models.PositiveIntegerField(null=True, unique=True)
    cama_numero =models.PositiveIntegerField(null=True)
    fecha_evento_principal = models.DateField(null=True)
    hora_evento_principal = models.TimeField(blank=True, null=True)
    fecha_hora_ingreso = models.DateTimeField(null=True)

    ######## Grupo diagnostico
    TCE='TCE'
    H_A='Hipoxia/Anoxia'
    ACV='ACV'
    G_diagnostico_choices=((TCE, u'TCE'),(H_A, u'Hipoxia/Anoxia'),(ACV, u'ACV'))
    G_diagnostico=models.CharField(max_length=20, choices=G_diagnostico_choices, null=True)
    ######## Diagnosticos neuro / psiquiatricos previos
    D_neuro_logico_psiquiatrico_previo=models.ManyToManyField(Dprevio, blank=True)
    ###### Especificacion diagnosticos
    D_especificos = models.TextField(blank=True, null=True)
    ######## criterios de inclusion
    criterios_CHOICES = (
        ('Paciente con episodio de parada cardíaca con reanimación exitosa', 'Paciente con episodio de parada cardíaca con reanimación exitosa'),
        ('Paciente con Dx de lesión cerebral aguda de origen traumático', 'Paciente con Dx de lesión cerebral aguda de origen traumático'),
        ('Paciente con Dx de lesión cerebral aguda por evento cerebrovascular', 'Paciente con Dx de lesión cerebral aguda por evento cerebrovascular'),

    )
    ci = models.CharField(choices=criterios_CHOICES, max_length=128, null=True, default='Paciente con episodio de parada cardíaca con reanimación exitosa',blank=True)
    ci3 = models.NullBooleanField('Puntaje en escala Glasgow igual o menor a 8 después del evento inicial')
    ci4=models.NullBooleanField("Paciente transportable a un resonador")

    ####### Criterios de exclusion
    ce1=models.NullBooleanField("Diagnóstico de muerte cerebral en las primeras 48 horas del ingreso a UCI")
    ce2=models.NullBooleanField("Destruccion masiva del parénquima cerebral no rescatable por neurocirugía")
    ce3=models.NullBooleanField("Disfunción neurológica y/o neuropsiquiátrica previa")
    ce4=models.NullBooleanField("Decisión de la familia de no participar en estudios de investigación")
    #######
    #######resultado


    medico_responsable=models.ForeignKey(Medico, on_delete=models.SET_NULL, null=True)
    imagen = models.FileField(null=True, upload_to="img",blank=True)
    estado = models.PositiveIntegerField(null=True, default=0)
    inscrito = models.NullBooleanField(default=False)
    archivo = models.FileField(null=True, upload_to="img", blank=True)

    def __str__(self):
        return '{}'.format(self.sujeto_numero)

    def get_seguimiento(self):
        return self.seguimiento_set.all().order_by('fechaseguimiento')
    def get_radio(self):
        return self.cambioradiologia_set.all()
    def get_neuro(self):
        return self.neurologia_set.all().order_by('fechaneuro')
    def get_img(self):
        i=Picture.objects.get(slug=self.sujeto_numero)
        return i
    def get_realineacion(self):
        realineacion=Realineacion.objects.get(sujeto=self.sujeto_numero)
        return realineacion
    def get_snr(self):
        snr=Snr.objects.get(sujeto=self.sujeto_numero)
        return snr
    
    def get_path_imgs(self):
        I=img_to_show.objects.filter(sujeto=self.sujeto_numero)
        return I
    
    

    def delete(self, *args, **kwargs):
        """delete -- Remove to leave file."""
        c = self
        n=c.sujeto_numero
        shutil.rmtree(settings.MEDIA_ROOT+"/img/sujeto"+str(n), ignore_errors=True)
        super(Candidato, self).delete(*args, **kwargs)
        try:
            i=Picture.objects.get(slug=str(n))
            i.delete()
        except:
            ""

    class Meta:
        permissions = (
            ("can_descargar_candidato", u"puede descargar candidato"),
        )

    class ReportBuilder:
        exclude = ('nombres','apellidos','cc','imagen','id', 'archivo', )  # Lists or tuple of excluded fields


class Ingreso(models.Model):
    candidato = models.OneToOneField(Candidato, on_delete=models.CASCADE, null=True)
    fecha_form = models.DateField(null=True)
    lugar_nacimiento = models.CharField(max_length=80, null=True, default="")
    lugar_residencia = models.CharField(max_length=80, null=True, default="")
    direccion = models.CharField(max_length=60, null=True, blank=True)
    nombre_acompanante = models.CharField(max_length=50,null=True, default="")
    tel1 = models.PositiveIntegerField(null=True)
    tel2 = models.PositiveIntegerField(null=True, blank=True)
    peso =models.PositiveIntegerField(null=True, blank=True)
    estatura = models.PositiveIntegerField(null=True, blank=True)
    ####### nivel educativo
    Analfabeta = 'Analfabeta'
    primaria = 'Primaria'
    bachillerato = 'Bachillerato'
    tecnico = 'Técnico'
    profesional = 'Profesional'
    educativo_choices = ((Analfabeta, u'Analfabeta'),(primaria, u'Primaria'), (bachillerato, u'Bachillerato'), (tecnico, u'Técnico'), (profesional, u'Profesional'))
    n_educativo = models.CharField(max_length=20, choices=educativo_choices, null=True)
    ######
    ####### lateralidad
    diestro = 'Diestro'
    zurdo = 'Zurdo'
    ambidiestro = 'Ambidiestro'
    lateralidad_choices = ((diestro, u'Diestro'), (zurdo, u'Zurdo'), (ambidiestro, u'Ambidiestro'))
    lateralidad = models.CharField(max_length=20, choices=lateralidad_choices, null=True)
    ######
    ####### conciencia
    coma = 'Coma'
    svsr = 'SVSR'
    emc = 'EMC'
    conciencia_choices = ((coma, u'Coma'), (svsr, u'SVSR'), (emc, u'EMC'))
    conciencia = models.CharField(max_length=20, choices=conciencia_choices, null=True)
    ######
    sedado=models.NullBooleanField("Sedado por neuroprotección")
    a_patologicos = models.ManyToManyField(Apatologicos, blank=True)
    a_patologicos_cual= models.CharField(max_length=50, null=True,blank=True)


    fecha_craneotomia=models.DateField(blank=True, null=True)
    causa_quirurgicos = models.CharField(max_length=100, null=True, blank=True)

    a_toxico_alergenicos= models.CharField(max_length=50, null=True, blank=True)
    a_farmaco1=models.CharField(max_length=50, null=True, blank=True)
    a_farmaco1_dosis=models.CharField(max_length=30, null=True, blank=True)
    a_farmaco2 = models.CharField(max_length=50, null=True, blank=True)
    a_farmaco2_dosis = models.CharField(max_length=30, null=True, blank=True)
    a_familiares=models.CharField(max_length=50, null=True, blank=True)
    firma_consentimiento=models.BooleanField(default=True)
    firma_causa=models.CharField(max_length=50, null=True,blank=True)
    fechafirma=models.DateField(null=True, blank=True)
    archivo = models.FileField(null=True, upload_to="img", blank=True)
    archivofirma = models.FileField(null=True, upload_to="img", blank=True)

    def __str__(self):
        return '{}'.format(self.candidato.sujeto_numero)

    def delete(self, *args, **kwargs):
        """delete -- Remove to leave file."""
        self.archivo.delete(False)
        super(Ingreso, self).delete(*args, **kwargs)
    class Meta:
        permissions = (

templates/paciente/paciente_listar.html
{% extends 'base/base.html' %}

{% block title %} Listado de Sujetos {% endblock %}
{% block content %}



{% if perms.paciente.add_candidato %}
<button style="vertical-align: middle;" type="button" onclick="location.href='{% url 'paciente_crear' %}'" class="btn btn-success"><i class="glyphicon glyphicon-plus"></i> Añadir Registro</button>
{% endif %}
<br>
<br>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert alert-success">
    {{ message }}
  </div>
    {% endfor %}
</ul>
{% endif %}


<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#seguimiento">Observación</a>
  </li>
  <li class="nav-item active">
    <a class="nav-link active" data-toggle="tab" href="#admitidos">Incluidos</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" data-toggle="tab" href="#rechazados">Rechazados</a>
  </li>

</ul>
<div id="myTabContent" class="tab-content">
  <div class="tab-pane" id="seguimiento">

      {% if object_list|length == 0 %}
      <h2>No hay registros de Sujetos</h2>
      {% else %}

                <table class="table table-hover">
                  <thead>
                    <tr>
                      <th scope="col">&nbsp;&nbsp;&nbsp;Id</th>
                      <th scope="col">Profesional a cargo </th>
                      <th>Tiempo desde ingreso UCI</th>
                      {% if perms.paciente.change_candidato or perms.paciente.delete_candidato %}
                      <th style="text-align:right" scope="col">Acciones</th>
                      {% endif %}
                    </tr>
                  </thead>
                  <tbody>
                    {% if object_list %}
                        {% for object in object_list %}
                            {% if object.estado == 0 %}
                            {% load scripts %}
                            {% tiempo object as t%}
                            <tr class="table-active" >
                              <td><form><button class="btn btn-link enabled" formaction="{% url 'paciente' object.pk%}" title="Ver información">{{object.sujeto_numero|stringformat:"04d"}}</button></form></td>
                              <td style="vertical-align: middle;">{{object.medico_responsable}}</td>
                              <td>{{t}} Horas</td>
                              {% if perms.paciente.change_candidato or perms.paciente.delete_candidato %}
                              <td style="text-align:right">
                                  <form>

                                  {% if t >= 48  %}
                                  <button class="btn btn-primary" formaction="{% url 'paciente_editar' object.pk%}">Establecer Criterios</button>
                                  {% endif %}
                                  {% if perms.paciente.delete_candidato %}

                                  <button class="btn btn-danger"  formaction="{% url 'paciente_eliminar' object.pk%}" title="Eliminar">
                                  <i class="glyphicon glyphicon-trash"></i>

                                  </button>

                                  {% endif %}

                                  </form>

                              </td>


                              {% endif %}
                            </tr>
                            {% endif %}
                        {% endfor%}

                    {% else %}
                    <h2>No hay registros de Sujetos</h2>

                    {% endif %}
                  </tbody>
                </table>
        {% endif %}



        <ul class="pager">
            <li>
                {% if page_obj.has_previous %}
                 <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                {% endif %}
                </li>
            <li>
                {% if page_obj.has_next %}
                 <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                {% endif %}
            </li>
        </ul>
  </div>

  <div class="tab-pane active" id="admitidos">
    {% if object_list|length == 0 %}
      <h2>No hay registros de Sujetos</h2>
      {% else %}
                <div class="container">
                    <br>
                    <p>Total: {% totalincluidos %}</p>

                </div>
                <table class="table table-hover">

                  <thead>
                    <tr>
                      <th scope="col">&nbsp;&nbsp;&nbsp;Id</th>
                      <th scope="col">Profesional a cargo </th>
                      {% if user.groups.all.0.name == 'Residente' or user.groups.all.0.name == 'Coordinador' %}
                        <th scope="col">Seguimiento de hoy</th>
                      {% endif %}

                        {% if user.groups.all.0.name == 'Coordinador' %}
                        <th scope="col">Información Adicional</th>
                      {% endif %}

                        <th scope="col">Imágenes Cargadas</th>


                        
                     {% if perms.paciente.delete_candidato or  perms.paciente.can_descargar_candidato or perms.validacion.can_ver_slice %}
                      <th style="text-align:right" scope="col">Acciones</th>
                      {% endif %}
                    </tr>
                  </thead>
                  <tbody>
                    {% if object_list %}
                        {% for object in object_list %}
                            {% if object.estado > 0 and object.inscrito == True %}
                            <tr class="table-active" >
                              <td style="vertical-align: middle;"><form><button class="btn btn-link enabled" formaction="{% url 'paciente' object.pk%}" title="Ver información">{{object.sujeto_numero|stringformat:"04d"}}</button></form></td>
                              <td style="vertical-align: middle;">{{object.medico_responsable}}</td>
                              
                              {% if user.groups.all.0.name == 'Residente' or user.groups.all.0.name == 'Coordinador' %}
                                {% load scripts %}
                                <td style="vertical-align: middle;" scope="col">

                                    {% checkseguimiento object as check %}
                                    {% if check == 'si'  %}   <span style="color:green" class="glyphicon glyphicon-check" ></span> {% endif %}
                                    {% if check == 'no'  %}   <span style="color:red" class="glyphicon glyphicon-remove-circle"></span> {% endif %}
                                    {% if check != 'no' and check != 'si'  %}
                                    <p
                                    {% if check == "Formulario Ingreso UCI aún no cargado" %}
                                    style="color:red"
                                    {% endif %}
                                    >{{check}}
                                    </p>
                                    {% endif %}


                                </td>
                              {% endif %}

                                {% if user.groups.all.0.name == 'Coordinador' %}
                                    <th scope="col"><ul style="list-style-type:none">
                                        <li>cc: {{object.cc}}</li>
                                        <li>{{object.nombres}}</li>
                                        <li>{{object.apellidos}}</li>
                                        <li>HC: {{object.HC}}</li>
                                    </ul></th>
                                  {% endif %}

                                    <td style="vertical-align: middle;" scope="col">{% if object.imagen %} <span style="color:green" class="glyphicon glyphicon-check"></span> {% endif %}</td>




                              {% if perms.paciente.delete_candidato or  perms.paciente.can_descargar_candidato or perms.validacion.can_ver_slice %}
                              <td style="text-align:right;vertical-align: middle;" >
                                  <form>
                                      
                                {% if object.get_img and object.get_img.anonimo == 1 and perms.validacion.can_ver_slice %}
                              <button class="btn btn-info"  formaction="{% url 'pacienteviewimg' object.pk %}" title="Ver Imágenes">
                              <i class="glyphicon glyphicon-eye-open"></i>
                              </button>
                                  {% endif %}  
                                      
                                      
                                    {% if object.get_img and object.get_img.anonimo == 1 and perms.paciente.can_descargar_candidato %}
                                  <button class="btn btn-success"  formaction="{{ object.get_img.file.url }}" title="Descargar">
                                  <i class="glyphicon glyphicon-download"></i>
                                  </button>
                                      {% endif %}
                                  {% if perms.paciente.delete_candidato %}
                                  <button class="btn btn-danger"  formaction="{% url 'paciente_eliminar' object.pk%}" title="Eliminar">
                                  <i class="glyphicon glyphicon-trash"></i>
                                  </button>
                                  {% endif %}
                                    </form>



                              </td>
                              {% endif %}
                            </tr>
                            {% endif %}
                        {% endfor%}

                    {% else %}
                    <h2>No hay registros de Sujetos</h2>

                    {% endif %}
                  </tbody>
                </table>
        {% endif %}



        <ul class="pager">
            <li>
                {% if page_obj.has_previous %}
                 <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                {% endif %}
                </li>
            <li>
                {% if page_obj.has_next %}
                 <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                {% endif %}
            </li>
        </ul>
  </div>

  <div class="tab-pane fade" id="rechazados">
    {% if object_list|length == 0 %}
      <h2>No hay registros de Sujetos</h2>
      {% else %}
                <div class="container"><br><p>Total: {% totalexcluidos %}</p></div>
                <table class="table table-hover">
                  <thead>
                    <tr style="vertical-align: middle;" >
                      <th scope="col">&nbsp;&nbsp;&nbsp;Id</th>
                      <th scope="col">Profesional a cargo </th>
                        <th scope="col">Motivo Exclusión </th>
                      {% if perms.paciente.delete_candidato %}
                      <th style="text-align:right" scope="col">Acciones</th>
                      {% endif %}
                    </tr>
                  </thead>
                  <tbody>
                    {% if object_list %}
                        {% for object in object_list %}
                            {% if object.estado > 0 and object.inscrito == False %}
                            <tr class="table-active" id="fila{{object.sujeto_numero}}" >
                              <td><form><button class="btn btn-link enabled" formaction="{% url 'paciente' object.pk%}" title="Ver información">{{object.sujeto_numero|stringformat:"04d"}}</button></form></td>
                              <td style="vertical-align: middle;">{{object.medico_responsable}}</td>
                                <td scope="col" style="vertical-align: middle;">

                                    {% mexclusion object%}
                                </td>

                              {% if perms.paciente.delete_candidato %}
                              <td style="text-align:right">
                                  <form>
                                  <button class="btn btn-danger"  formaction="{% url 'paciente_eliminar' object.pk%}" title="Eliminar">
                                  <i class="glyphicon glyphicon-trash"></i>
                                  </button>
                                  </form>
                              </td>
                              {% endif %}
                            </tr>
                            {% endif %}
                        {% endfor%}

                    {% else %}
                    <h2>No hay registros de Sujetos</h2>

                    {% endif %}
                  </tbody>
                </table>
        {% endif %}



        <ul class="pager">
            <li>
                {% if page_obj.has_previous %}
                 <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
                {% endif %}
                </li>
            <li>
                {% if page_obj.has_next %}
                 <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                {% endif %}
            </li>
        </ul>
  </div>

</div>








{% endblock %}