SanJose/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include
from django.contrib.auth import views
from django.views.generic import TemplateView
from django.contrib.auth.views import logout

from .views import error, crearingreso, crearradiologia, crearuci, crearneurologia, crearbold, crearinformante, \
    crearseguimiento, crearradiologiaf, crearmoca, crearnps, crearneuropsi, visionimagen, validarmovimiento, alinear, crearlectura

from .views import reportes, run_pipeline

urlpatterns = [
    path('', lambda x: HttpResponseRedirect('/login')),
    path('admin/', admin.site.urls),
    path('carga/', include('apps.fileupload.urls')),
    path('paciente/', include('apps.paciente.urls')),
    path('validacion/', include('apps.validacion.urls')),
    path('graficas/',include('apps.graphs.urls')),

    url(r'^login/$', views.login, name='login'),
    url(r'^accounts/logout/$', logout, {'template_name': 'registration/logout.html'},name='logout'),
    url(r'^login-error$', error, name='login-error'),
    path('report_builder/', include('report_builder.urls')),
    path('script/creari/<int:pk>/', crearingreso, name='crear_ingreso'),
    path('script/crearr/<int:pk>/', crearradiologia, name='crear_radiologia'),
    path('script/crearu/<int:pk>/', crearuci, name='crear_uci'),
    path('script/crearn/<int:pk>/', crearneurologia, name='crear_neurologia'),
    path('script/crearb/<int:pk>/', crearbold, name='crear_bold'),
    path('script/crearinf/<int:pk>/', crearinformante, name='crear_informante'),
    path('script/crears/<int:pk>/', crearseguimiento, name='crear_seguimiento'),
    path('script/crearrf/<int:pk>/<slug:razon>/', crearradiologiaf, name='crear_rf'),
    path('script/crearnps/<int:pk>/<slug:razon>/<slug:fecha>/', crearnps, name='crear_nps'),
    path('script/crearm/<int:pk>/', crearmoca, name='crear_moca'),
    path('script/crearnpsi/<int:pk>/', crearneuropsi, name='crear_neuropsi'),
    path('script/crearl/<int:pk>/<slug:tipo>/', crearlectura, name='crear_lectura'),
    path('script/filtros_img/<slug:pk>/', visionimagen, name='vision_img'),
    path('script/vmovimiento/<slug:tipo>/<int:pk>/<slug:v1>/<slug:v2>/', validarmovimiento, name='v_movimiento'),
    path('script/alinear/<slug:tipo>/<int:pk>/<slug:img>/<slug:der>/<slug:frente>/<slug:arriba>/<slug:x>/<slug:y>/<slug:z>/<slug:tx>/<slug:ty>/<slug:tz>/<slug:save>/', alinear, name='alinear'),

  
    url(r'^reportes$',reportes,name="reportes"),

    url(r'^visualizador', TemplateView.as_view(template_name='slicedrop/index.html'), name="visor"),

    url(r'^accounts/', include('allauth.urls')),
    
    path('procesamiento/', include('apps.procesamiento.urls')),
    
    path('script/run_pipeline/<int:user_pk>/<int:img_pk>/<int:pipeline_pk>/', run_pipeline, name='run_pipeline'),




]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/procesamiento/urls.py
from django.conf.urls import url


from django.urls import path


from apps.procesamiento.views import TaskgroupCreate, TaskgroupUpdate, TaskgroupList, TaskgroupDelete, PipelineCreate, PipelineUpdate, PipelineDelete, Multi, resultados_list


urlpatterns = [
	path('grupos/crear', TaskgroupCreate.as_view(), name='grupo_crear'),
	path('grupos/editar/<int:pk>/', TaskgroupUpdate.as_view(), name='grupo_editar'),
	path('grupos/listar/', TaskgroupList.as_view(), name='grupo_listar'),
	path('grupos/eliminar/<int:pk>/', TaskgroupDelete.as_view(), name='grupo_eliminar'),    
	path('pipeline/crear', PipelineCreate.as_view(), name='pipeline_crear'),
	path('pipeline/editar/<int:pk>/', PipelineUpdate.as_view(), name='pipeline_editar'),  
	path('pipeline/eliminar/<int:pk>/', PipelineDelete.as_view(), name='pipeline_eliminar'),    
	url(r'^multi_run',Multi,name="multi_run"),
    
	path('resultados/<int:pk>', resultados_list.as_view(), name='resultados'),    
]

apps/procesamiento/models.py
from django.db import models

from apps.validacion.models import Tipoimagenes
from django.contrib.auth.models import Group, Permission, User
from apps.fileupload.models import Picture
# Create your models here.


class Task(models.Model):
    nombre = models.CharField(max_length=100)
    pathscript = models.CharField(max_length=150)
    dependencia = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, default=None, blank=True)
    habilitado = models.BooleanField(default=True)
    tipo_imagen = models.ForeignKey(Tipoimagenes, on_delete=None)

    def __str__(self):
        return '{}'.format(self.nombre)
    
class default_result(models.Model):

    nombre=models.CharField(max_length=100)
    task=models.ForeignKey(Task, on_delete=models.CASCADE)
    word_key=models.CharField(max_length=100)
    
    imagen='Imagen'
    grafica='Grafica'
    text="Texto"
    nii="Archivo nii"
    trk="Archivo trk"
    csv="Archivo csv"
    ica="Ica Component"
    g_ica="Ica Graph"
    
    tipo_choices=((imagen, u'Imagen'),(grafica, u'Grafica'),(text, u'Texto'),(nii, u'Archivo nii'),(trk, u'Archivo trk'),(csv, u'Archivo csv'),(ica, u'Ica Component'),(g_ica, u'Ica Graph'))
    tipo=models.CharField(max_length=40, choices=tipo_choices, null=True)    
    def __str__(self):
        return '{}'.format(self.nombre)

class Taskgroup(models.Model):

    nombre=models.CharField(max_length=100)
    task=models.ManyToManyField(Task, blank=True)
    orden=models.CharField(max_length=200,null=True)
    tipo_imagen = models.ForeignKey(Tipoimagenes, on_delete=models.CASCADE)
    dependencia = models.ForeignKey('self',on_delete=models.SET_NULL,null=True,default=None,blank=True)
    eliminable = models.BooleanField(default=True)
    def __str__(self):
        return '{}'.format(self.nombre)

    def get_tasks(self):
        orden=self.orden
        lista=orden.split("_")[:-1]
        tareas = []
        
        for i in lista:
            tareas.append(Task.objects.get(pk=int(i)))
            
        return tareas
        
class Pipeline(models.Model):

    nombre=models.CharField(max_length=100)
    grupos=models.ManyToManyField(Taskgroup, blank=True)
    orden=models.CharField(max_length=200,null=True)
    tipo_imagen = models.ForeignKey(Tipoimagenes, on_delete=models.CASCADE)
    dependencia = models.ForeignKey('self',on_delete=models.SET_NULL,null=True,default=None,blank=True)
    eliminable = models.BooleanField(default=True)
    def __str__(self):
        return '{}'.format(self.nombre)

    def get_groups(self):
        orden=self.orden
        lista=orden.split("_")[:-1]
        groups = []
        
        for i in lista:
            groups.append(Taskgroup.objects.get(pk=int(i)))
            
        return groups
        
        
class task_celery(models.Model):

    id_task=models.CharField(max_length=200,default="",blank=True,null=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    imagen = models.ForeignKey(Picture,on_delete=models.CASCADE,null=True)
    pipeline = models.ForeignKey(Pipeline,on_delete=models.CASCADE,null=True)
    estado = models.CharField(max_length=100)
    
    
    
    
    def __str__(self):
        return '%s - proceso %s' % (self.imagen.slug,self.pipeline.nombre)

        
        
class results(models.Model):

    task_celery = models.ForeignKey(task_celery,on_delete=models.CASCADE,null=True)
    nombre=models.CharField(max_length=100)
    path = models.CharField(max_length=250)
    
    imagen='Imagen'
    grafica='Grafica'
    text="Texto"
    nii="Archivo nii"
    trk="Archivo trk"
    csv="Archivo csv"
    ica="Ica Component"
    g_ica="Ica Graph"
    
    tipo_choices=((imagen, u'Imagen'),(grafica, u'Grafica'),(text, u'Texto'),(nii, u'Archivo nii'),(trk, u'Archivo trk'),(csv, u'Archivo csv'),(ica, u'Ica Component'),(g_ica, u'Ica Graph'))
    tipo=models.CharField(max_length=40, choices=tipo_choices, null=True)
    
    def __str__(self):
        return 'imagen:  %s - nombre: %s' % (self.task_celery.imagen,self.nombre)
        

apps/procesamiento/forms.py
from django import forms

from apps.procesamiento.models import Taskgroup, Task, Pipeline


    
class gruposForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super().__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['dependencia'].required = False
    
    class Meta:
        model = Taskgroup


        fields = [
            'nombre',
            'tipo_imagen',
            'orden',
            'dependencia',

        ]

        labels = {
            'nombre':"Nombre",
            'orden':"Orden",
            'tipo_imagen':"Tipo de Imagen",
            'dependencia':"Dependencia",


        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': "off"}),
            'orden': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': "off"}),
            'tipo_imagen': forms.Select(attrs={'class': 'form-control'}),
            'dependencia': forms.Select(attrs={'required': 'false'}),
        }
        
class PipelineForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super().__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['dependencia'].required = False
    
    class Meta:
        model = Pipeline


        fields = [
            'nombre',
            'tipo_imagen',
            'orden',
            'dependencia',

        ]

        labels = {
            'nombre':"Nombre",
            'orden':"Orden",
            'tipo_imagen':"Tipo de Imagen",
            'dependencia':"Dependencia",


        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': "off"}),
            'orden': forms.TextInput(attrs={'class': 'form-control', 'autocomplete': "off"}),
            'tipo_imagen': forms.Select(attrs={'class': 'form-control'}),
            'dependencia': forms.Select(attrs={'required': 'false'}),
        }
        
class MultiForm(forms.Form):
    user = forms.CharField(max_length = 100)
    lista_img = forms.CharField(max_length = 500)
    pipeline_pk = forms.CharField(max_length = 100)

apps/procesamiento/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
# Create your views here.

from apps.procesamiento.forms import gruposForm, PipelineForm, MultiForm
from apps.procesamiento.models import Taskgroup, Task, Pipeline, task_celery
from apps.validacion.models import Tipoimagenes

from django.views.generic import CreateView, UpdateView, ListView, DeleteView, DetailView
from SanJose.views import run_pipeline


class TaskgroupCreate(CreateView):
	model = Taskgroup
	form_class = gruposForm
	template_name = 'procesamiento/taskgroup_form.html'

	def get_success_url(self):
		G=self.object
		orden=G.orden
		for t in orden.split('_')[:-1]:
			G.task.add(Task.objects.get(pk=int(t)))
		G.save()
        
		return reverse_lazy('grupo_listar')

class TaskgroupUpdate(UpdateView):
	model = Taskgroup
	form_class = gruposForm
	template_name = 'procesamiento/taskgroup_form.html'

	def get_success_url(self):
		G=self.object
		G.task.clear()
		orden=G.orden
		for t in orden.split('_')[:-1]:
			G.task.add(Task.objects.get(pk=int(t)))
		G.save()
        
		return reverse_lazy('grupo_listar')
    
class TaskgroupList(ListView):
	model = Taskgroup
	template_name = 'procesamiento/taskgroup_listar.html'
    
class TaskgroupDelete(DeleteView):
    model = Taskgroup
    # a donde va dirigido
    template_name = 'procesamiento/taskgroup_eliminar.html'
    def get_success_url(self):
        
        return reverse_lazy('grupo_listar')
    
class PipelineCreate(CreateView):
	model = Pipeline
	form_class = PipelineForm
	template_name = 'procesamiento/pipeline_form.html'

	def get_success_url(self):
		P=self.object
		orden=P.orden
		for t in orden.split('_')[:-1]:
			P.grupos.add(Taskgroup.objects.get(pk=int(t)))
		P.save()
        
		return reverse_lazy('grupo_listar')
    
class PipelineUpdate(UpdateView):
	model = Pipeline
	form_class = PipelineForm
	template_name = 'procesamiento/pipeline_form.html'

	def get_success_url(self):
		P=self.object
		P.grupos.clear()        
		orden=P.orden
		for t in orden.split('_')[:-1]:
			P.grupos.add(Taskgroup.objects.get(pk=int(t)))
		P.save()
        
		return reverse_lazy('grupo_listar')
    
class PipelineDelete(DeleteView):
    model = Pipeline
    # a donde va dirigido
    template_name = 'procesamiento/pipeline_eliminar.html'
    def get_success_url(self):
        
        return reverse_lazy('grupo_listar')
    
def Multi(request):
    
    form = MultiForm()
    
    if request.method == "POST":
        form = MultiForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data
            user_pk=data['user']
            lista=data['lista_img']
            p_pk=data['pipeline_pk']
            imgs=lista.split('_')[:-1]
            for img in imgs:
                run_pipeline(request,user_pk,img,p_pk)
            
            
            
        form = MultiForm()
        return render(request, 'procesamiento/multi.html', {'form': form})
    
    if request.method == "GET":
        form = MultiForm()
    
    return render(request, 'procesamiento/multi.html', {'form': form})

    
class resultados_list(DetailView):
	model = task_celery
	template_name = 'procesamiento/resultados.html'
    

templates/procesamiento/pipeline_eliminar.html
{% extends 'base/base.html' %}

{% block content %}

{% if not object.eliminable %}
<script type="text/javascript">
        window.location="{% url 'login' %}";
</script>
{% endif %}

<center>
<div class="container">
    <form method="post">
	    {% csrf_token %}
	    <h3>¿Desea eliminar el Pipeline {{ object }}?</h3>


	    <button class="btn btn-danger" type="submit">Sí, eliminar</button>
	    <a class="btn btn-success" href="{% url 'grupo_listar' %}">Cancelar</a>
	</form>
</div>
</center>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/static/js/tmpl.min.js"></script>
<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
<script src="/static/js/bootstrap.min.js"></script>

<!-- The XDomainRequest Transport is included for cross-domain file deletion for IE8+ -->
<!--[if gte IE 8]>
<script src="/static/js/cors/jquery.xdr-transport.js"></script>
<![endif]-->

{% endblock %}

templates/procesamiento/pipeline_form.html
{% extends 'base/base.html' %}

{% block title %} Formulario Pipelines {% endblock %}
{% block content %}


{% if object %}
{% if not object.eliminable %}
    {% if not  user.is_superuser  %}
    <script type="text/javascript">
            window.location="{% url 'login' %}";
    </script>
    {% endif %}
{% endif %}
{% endif %}

{% load scripts_validacion %}
{% load scripts_procesamiento %}


<style>
#div1,#div2 {
  float: center;
  width: 100%;
  height: 250px;
  margin: 10px;
  padding: 10px;
  border: 1px solid black;
  text-align: center;
  overflow: auto;
}

</style>






<form method="post">

    

    {% csrf_token %}

    <div class="col-md-8 col-md-offset-2">
        <h2>Creación de Pipelines</h2>
        <br>
      <label >Nombre : </label>
        
      {{form.nombre}}
      
        
        <br>
        

        {% get_img_with_tasks as images %}
        
        <label >Tipo de Imagen : </label>
        <select required="required"  onchange="mostrar()" id="id_tipo_imagen" name='tipo_imagen'>
            <option value="">---------------</option>
            {% for img in images %}
                <option value="{{img.pk}}" {% if object.tipo_imagen.pk == img.pk %} selected {% endif %}>{{img.nombre}}</option>
            {% endfor %}
       </select>

       
        
        
        <label for="id_dependencia">Dependencia:</label>
        <select name="dependencia" id="id_dependencia">
          <option value="" >---------</option>
            {% get_pipelines as pipe %}
          {% for p in pipe %}
                <option value="{{p.pk}}" {% if object.dependencia.pk == p.pk %} selected {% endif %} >{{p}}</option>
            {% endfor %}

        </select>

        
        
        
        <div id="div1" ondrop="drop(event)" ondragover="allowDrop(event)">
        <h4>Grupos relacionados a la imagen</h4>
        <hr  />
            
         {% for img in images %}
        
        {% get_groups_for_images img  as tasks %}
        

        {% for task in tasks %}
            <h4 class="column" draggable="true" ondragstart="drag(event)" id="{{task.pk}}" {% if task.dependencia %} title="{{task.dependencia}}" {% endif %} style="background-color:powderblue; display:none" >{{task}} </h4>

        {% endfor %}
       
      {% endfor %}
        

        </div>

        <br>
        * Nota: Tener en cuenta las dependencias que existen entre los grupos, estas se muestran poniendo el cursor sobre una de ellas.
        
        <br>
        <div id="div2" ondrop="drop(event)" ondragover="allowDrop(event)">
            <h4>Grupos Escogidos Para el Pipeline</h4>
        <h5>Arrastre desde el recuadro de arriba para elegir las tareas y su orden</h5>
        <hr  />
        
        </div>

        

      <br>

      
     
        

       
        {{form.orden.as_hidden}}

      
    

       <br>
       <br>
      <button class="btn btn-primary" id="guardar" type="submit">Guardar</button>  
    </div>

    

    
    

</form>



<script>
    function mostrar() {

     document.getElementById("div1").innerHTML = '<h4>Grupos relacionados a la imagen</h4> <hr  />  {% for img in images %}  {% get_groups_for_images img  as tasks %} {% for task in tasks %} <h4 class="column" draggable="true" ondragstart="drag(event)" id="{{task.pk}}" name="{{img.pk}}" {% if task.dependencia %} title="{{task.dependencia}}" {% endif %} style="background-color:powderblue; display:none" >{{task}} </h4>        {% endfor %}     {% endfor %}      ';
        
    document.getElementById("div2").innerHTML = ' <h4>Grupos Escogidos Para el Pipeline</h4>      <h5>Arrastre desde el recuadro de arriba para elegir las tareas y su orden</h5>     <hr  />';
 
        
      document.getElementById("id_orden").value="";  
      var z = document.getElementsByClassName("column");
        var i;
      for (i = 0; i < z.length; i++) {
          z[i].style="display:none";
          
      }
        
        
      var x = document.getElementById('id_tipo_imagen').value;
      var y = document.getElementsByName(x);
      var i;
      for (i = 0; i < y.length; i++) {
          y[i].style="display:onblock";
          y[i].style="background-color:powderblue";
      }
        
    }
    
    function terminar() {
        var c = document.getElementById("div2").childNodes
        var x = "";
        for (i = 0; i < c.length; i++) {
        
              if(Number.isInteger(parseInt(c[i].id)) == true){
                  x+=c[i].id+"_";
              
              };
            
        
            
          }
        document.getElementById("id_orden").value=x;
        
    }
    
    
    function allowDrop(ev) {
      ev.preventDefault();
    }

    function drag(ev) {
      ev.dataTransfer.setData("text", ev.target.id);
    }

    function drop(ev) {
      ev.preventDefault();
      var data = ev.dataTransfer.getData("text");
      ev.target.appendChild(document.getElementById(data));
      terminar();
    }  
    
    
</script>

{% if object %}
<script>
    mostrar()
    document.getElementById("div1").innerHTML = '<h4>Grupos relacionados a la imagen</h4> <hr  />    {% get_groups_for_images object.tipo_imagen  as tasks %} {% for task in tasks %} {% if task not in object.get_groups %} <h4 class="column" draggable="true" ondragstart="drag(event)" id="{{task.pk}}" name="{{img.pk}}" {% if task.dependencia %} title="{{task.dependencia}}" {% endif %} style="background-color:powderblue; display:onblock" >{{task}} </h4>   {% endif %}{% endfor %}  ';
    
    document.getElementById("div2").innerHTML = '<h4>Grupos Escogidos Para el Pipeline</h4> <hr  />  {% get_groups_for_images object.tipo_imagen  as tasks %} {% for task in tasks %} {% if task in object.get_groups %} <h4 class="column" draggable="true" ondragstart="drag(event)"id="{{task.pk}}" name="{{img.pk}}" {% if task.dependencia %} title="{{task.dependencia}}" {% endif %} style="background-color:powderblue; display:onblock" >{{task}} </h4>        {% endif %}{% endfor %}  ';
    
    document.getElementById("id_orden").value="{{object.orden}}";
    
    
</script>
{% endif %}


{% endblock %}

templates/procesamiento/taskgroup_eliminar.html
{% extends 'base/base.html' %}

{% block content %}

{% if not object.eliminable  %}
<script type="text/javascript">
        window.location="{% url 'login' %}";
</script>
{% endif %}


<center>
<div class="container">
    <form method="post">
	    {% csrf_token %}
	    <h3>¿Desea eliminar el Grupo de Tareas {{ object }}?</h3>


	    <button class="btn btn-danger" type="submit">Sí, eliminar</button>
	    <a class="btn btn-success" href="{% url 'grupo_listar' %}">Cancelar</a>
	</form>
</div>
</center>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<!-- The jQuery UI widget factory, can be omitted if jQuery UI is already included -->
<script src="/static/js/tmpl.min.js"></script>
<!-- Bootstrap JS is not required, but included for the responsive demo navigation -->
<script src="/static/js/bootstrap.min.js"></script>

<!-- The XDomainRequest Transport is included for cross-domain file deletion for IE8+ -->
<!--[if gte IE 8]>
<script src="/static/js/cors/jquery.xdr-transport.js"></script>
<![endif]-->

{% endblock %}

templates/procesamiento/taskgroup_form.html
{% extends 'base/base.html' %}

{% block title %} Formulario Grupo de Tareas {% endblock %}
{% block content %}

{% if object %}
{% if not object.eliminable %}
    {% if not  user.is_superuser  %}
    <script type="text/javascript">
            window.location="{% url 'login' %}";
    </script>
    {% endif %}
{% endif %}
{% endif %}



{% load scripts_validacion %}
{% load scripts_procesamiento %}


<style>
#div1,#div2 {
  float: center;
  width: 100%;
  height: 250px;
  margin: 10px;
  padding: 10px;
  border: 1px solid black;
  text-align: center;
  overflow: auto;
}

</style>






<form method="post">

    

    {% csrf_token %}

    <div class="col-md-8 col-md-offset-2">
        <h2>Creación de Grupo de Tareas</h2>
        <br>
      <label >Nombre : </label>
        
      {{form.nombre}}
      
        
        <br>
        
        {% get_img_with_tasks as images %}
        
        <label >Tipo de Imagen : </label>
        <select required="required"  onchange="mostrar()" id="id_tipo_imagen" name='tipo_imagen'>
            <option value="">---------------</option>
            {% for img in images %}
                <option value="{{img.pk}}" {% if object.tipo_imagen.pk == img.pk %} selected {% endif %}>{{img.nombre}}</option>
            {% endfor %}
       </select>

       
        
        
        <label for="id_dependencia">Dependencia:</label>
        <select name="dependencia" id="id_dependencia">
          <option value="" >---------</option>
            {% get_taskgroups as grupos %}
          {% for g in grupos %}
                <option value="{{g.pk}}" {% if object.dependencia.pk == g.pk %} selected {% endif %} >{{g}}</option>
            {% endfor %}

        </select>

        
        
        
        <div id="div1" ondrop="drop(event)" ondragover="allowDrop(event)">
        <h4>Tareas relacionadas a la imagen</h4>
        <hr  />
            
         {% for img in images %}
        
        {% get_task_for_images img  as tasks %}
        

        {% for task in tasks %}
            <h4 class="column" draggable="true" ondragstart="drag(event)" {% if task.dependencia %} title="{{task.dependencia}}" {% endif %} id="{{task.pk}}" style="background-color:powderblue; display:none" >{{task}} </h4>

        {% endfor %}
       
      {% endfor %}
        

        </div>

        <br>
        * Nota: Tener en cuenta las dependencias que existen entre las tareas, estas se muestran poniendo el cursor sobre una de ellas.
        
        <br>
        <div id="div2" ondrop="drop(event)" ondragover="allowDrop(event)">
            <h4>Tareas Escogidas Para el grupo de tareas</h4>
        <h5>Arrastre desde el recuadro de arriba para elegir las tareas y su orden</h5>
        <hr  />
        
        </div>

        

      <br>

      
     
        

       
        {{form.orden.as_hidden}}

      
    

       <br>
       <br>
      <button class="btn btn-primary" id="guardar" type="submit">Guardar</button>  
    </div>

    

    
    

</form>



<script>
    function mostrar() {

     document.getElementById("div1").innerHTML = '<h4>Tareas relacionadas a la imagen</h4> <hr  />  {% for img in images %}  {% get_task_for_images img  as tasks %} {% for task in tasks %} <h4 class="column" draggable="true" ondragstart="drag(event)" id="{{task.pk}}" name="{{img.pk}}" {% if task.dependencia %} title="{{task.dependencia}}" {% endif %} style="background-color:powderblue; display:none" >{{task}} </h4>        {% endfor %}     {% endfor %}      ';
        
    document.getElementById("div2").innerHTML = ' <h4>Tareas Escogidas Para el grupo de tareas</h4>      <h5>Arrastre desde el recuadro de arriba para elegir las tareas y su orden</h5>     <hr  />';
 
        
      document.getElementById("id_orden").value="";  
      var z = document.getElementsByClassName("column");
        var i;
      for (i = 0; i < z.length; i++) {
          z[i].style="display:none";
          
      }
        
        
      var x = document.getElementById('id_tipo_imagen').value;
      var y = document.getElementsByName(x);
      var i;
      for (i = 0; i < y.length; i++) {
          y[i].style="display:onblock";
          y[i].style="background-color:powderblue";
      }
        
    }
    
    function terminar() {
        var c = document.getElementById("div2").childNodes
        var x = "";
        for (i = 0; i < c.length; i++) {
        
              if(Number.isInteger(parseInt(c[i].id)) == true){
                  x+=c[i].id+"_";
              
              };
            
        
            
          }
        document.getElementById("id_orden").value=x;
        
    }
    
    
    function allowDrop(ev) {
      ev.preventDefault();
    }

    function drag(ev) {
      ev.dataTransfer.setData("text", ev.target.id);
    }

    function drop(ev) {
      ev.preventDefault();
      var data = ev.dataTransfer.getData("text");
      ev.target.appendChild(document.getElementById(data));
      terminar();
    }  
    
    
</script>

{% if object %}
<script>
    mostrar()
    document.getElementById("div1").innerHTML = '<h4>Tareas relacionadas a la imagen</h4> <hr  />    {% get_task_for_images object.tipo_imagen  as tasks %} {% for task in tasks %} {% if task not in object.get_tasks %} <h4 class="column" draggable="true" ondragstart="drag(event)" id="{{task.pk}}" name="{{img.pk}}" {% if task.dependencia %} title="{{task.dependencia}}" {% endif %} style="background-color:powderblue; display:onblock" >{{task}} </h4>   {% endif %}{% endfor %}  ';
    
    document.getElementById("div2").innerHTML = '<h4>Tareas relacionadas a la imagen</h4> <hr  />  {% get_task_for_images object.tipo_imagen  as tasks %} {% for task in tasks %} {% if task in object.get_tasks %} <h4 class="column" draggable="true" ondragstart="drag(event)"id="{{task.pk}}" name="{{img.pk}}" {% if task.dependencia %} title="{{task.dependencia}}" {% endif %} style="background-color:powderblue; display:onblock" >{{task}} </h4>        {% endif %}{% endfor %}  ';
    
    document.getElementById("id_orden").value="{{object.orden}}";
    
    
</script>
{% endif %}


{% endblock %}